version: 2.1

jobs:
  my-cool-job:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "hello"

workflows:
  my-workflow:
    jobs:
      - my-cool-job:
          serial-group: "https://github.com/parkuman/learning-circleci/pulls/1"
