version: 2.1

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    parameters:
      message:
        type: string
    steps:
      - run: echo "<< parameters.message >>"

workflows:
  main:
    jobs:
      - echo:
          serial-group: << pipeline.project.slug >>/echo-group
          matrix:
            parameters:
              message:
                - "hello"
                - "world"
                - "goodbye"
