version: 2.1

parameters:
  run-all:
    type: boolean
    default: false

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Hello from continuation
          command: echo "Hello from the continued pipeline!"

  say-goodbye:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Goodbye from continuation
          command: echo "Goodbye from the continued pipeline!"

workflows:
  continued-workflow-1:
    when: << pipeline.parameters.run-all >>
    jobs:
      - say-hello

  continued-workflow-2:
    when: << pipeline.parameters.run-all >>
    jobs:
      - say-goodbye
